name: Docker Build
on:
  push:
    branches:
      - 'main'
jobs:
  BuildDocker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          pull: true
          push: true
          tags: ghcr.io/patrick246/k8s-outdated-image-exporter:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
